title: Machine Learning 2022-2
description: Pingdingshan University, Pingdingshan, China
sitename: Machine Learning
baseurl: '/ml-2022-2'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
